# Generated by Django 5.2.6 on 2025-09-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='age',
            new_name='roll',
        ),
        migrations.AddField(
            model_name='students',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_app.classname'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.classname')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='SubjectName',
            field=models.ManyToManyField(to='test_app.subjectname'),
        ),
        migrations.CreateModel(
            name='TeacherName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.classname')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.subjectname')),
            ],
        ),
    ]
