# Generated by Django 5.2.6 on 2025-09-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_classname_rename_name_students_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachername',
            name='class_name',
        ),
    ]
